title: Roger A. | Cybersecurity Portfolio
description: A.S. Cybersecurity Coursework & Labs
theme: jekyll-theme-hacker
show_downloads: false
# Add this section
header_pages:
  - index.md
  - labs.md
  - resume.md
